Controllers/RMA_DCEController.cs
using RMA_Docker.Classes;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RMA_Docker.Models;
using aspnet_mvc_razor_app.Controllers;
using Newtonsoft.Json;
using aspnet_mvc_razor_app.Classes;

namespace RMA_Docker.Controllers {

    [Authorize]
    public class RMA_DCEController : OCRController {

        //default loading page for New Template page.
        public ActionResult AddDocument() {
            return View();
        }

        public JsonResult UploadTemplate() {
            String retJsonMsg = String.Empty;
            foreach (String file in Request.Files) {
                var fileContent = Request.Files[file];
                var docType = Request.Form["DocType"];
                var docDesc = Request.Form["DocDesc"];
                var skipPages = Request.Form["SkipPages"];
                List<int> pagesToSkill = new List<int>();
                if (skipPages.Length > 0) {
                    List<String> skippages = skipPages.Split(',').ToList();
                    foreach (String skip in skippages) {
                        int number;
                        bool retInt = int.TryParse(skip, out number);
                        if (retInt) { pagesToSkill.Add(number); }
                        else { retJsonMsg = "ERROR - Skip page value ["+skip+"] is not a number!"; break; }
                    }
                }
                if (fileContent != null && fileContent.ContentLength > 0 && String.IsNullOrEmpty(retJsonMsg)) {
                    String virtualPath = UtilityOperations.GetDCEDockerRootPath();
                    String physicalPath = DecodePath(Path.Combine(UtilityOperations.GetServerMapPath(virtualPath), Path.GetFileName(fileContent.FileName)));
                    String userName = HttpContext.User.Identity.Name;
                    DocumentsOperations docOps = new DocumentsOperations(); 
                    if (docOps.GetFileByVirtualPath(virtualPath + "/" + fileContent.FileName) == null) {
                        System.IO.Directory.CreateDirectory(UtilityOperations.GetServerMapPath(virtualPath));
                        fileContent.SaveAs(physicalPath);
                        docOps.InsertFileEncodeFileName(fileContent.FileName, virtualPath + "/" + fileContent.FileName, "_DCEDockerFile", docDesc, userName, false);
                        DCEOperations dceOps = new DCEOperations();
                        dceOps.InsertTemplate(virtualPath + "/" + fileContent.FileName, docType, docDesc, userName);
                        List<String> retStrArr = GetPDFContents(physicalPath, pagesToSkill);
                        dceOps.InsertOCRContents(fileContent.FileName, retStrArr[0], retStrArr[1]);
                    } else { retJsonMsg = "ERROR - The file already eixsts."; }
                }
            }
            return new JsonResult() { Data = retJsonMsg };
        }

        public JsonResult GetUploadedTemplates() {
            DCEOperations dceOps = new DCEOperations();
            List<UploadedTemplates> listAllTemplates = new List<UploadedTemplates>();
            foreach (DCE_Templates template in dceOps.getAllUploadedTemplates()) {
                listAllTemplates.Add(new UploadedTemplates{
                    Name = template.Name,
                    DocumentType = template.DocumentType,
                    VirtualPath = template.VirtualPath,
                    DateTimeUploaded = template.DateTimeUploaded.ToString(),
                    Description = template.Description,
                    FileID = template.FileID
                });
            }
            return Json(new { Total = listAllTemplates.Count, Data = listAllTemplates });
        }

        [HttpPost]
        public JsonResult DeleteTemplate(String virtualPath) {
            bool retJsonBool = false;
            DocumentsOperations docOps = new DocumentsOperations();
            if (docOps.GetFileByVirtualPath(virtualPath) != null) {
                DCEOperations dceOps = new DCEOperations();
                Guid fileID = dceOps.GetFileIDFromTemplateByVirtualPath(virtualPath);
                if (fileID != Guid.Empty) {
                    dceOps.DeleteUploadedTemplateKeywords(fileID);
                    dceOps.DeleteUploadedTemplates(virtualPath);
                    docOps.DeleteFile(virtualPath);
                    String physicalPath = UtilityOperations.GetServerMapPath(virtualPath);
                    physicalPath = DecodePath(physicalPath);
                    if (System.IO.File.Exists(physicalPath)) { System.IO.File.Delete(physicalPath); }
                    retJsonBool = true;
                }
            }
            return new JsonResult() { Data = retJsonBool };
        }

        private String DecodePath(String path) {
            if (String.IsNullOrEmpty(path) || path == "/") { path = UtilityOperations.GetDockerRootPath(Server) + "/DCEDocker"; }
            String decodePath = path.Replace("/", "\\");
            return decodePath;
        }

        public ActionResult GenerateKeywords(String virtualPath) {
            DCEOperations dceOps = new DCEOperations();
            TemplateKeywords templateKeywords = new TemplateKeywords();
            templateKeywords.Keywords = GetKeywordsByVirtualPath(virtualPath);
            DCE_Templates template = dceOps.GetTemplateByVirtualPath(virtualPath);
            if (template != null) {
                templateKeywords.Template = GenerateUploadedTemplates(template);
                templateKeywords.SkipPages = template.SkipPages;
            }
            templateKeywords.TemplateOCRContent = template.DocumentOCRContent;
            return View(templateKeywords);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult GenerateKeywords(TemplateKeywords templateKeywords, String virtualPath, String inputKeyword, String templateDocType, String submit) {
            DCEOperations dceOps = new DCEOperations();
            DCE_Templates template = dceOps.GetTemplateByVirtualPath(virtualPath);
            if (template != null) {
                templateKeywords.Template = GenerateUploadedTemplates(template);
                templateKeywords.SkipPages = template.SkipPages;
            }
            templateKeywords.TemplateOCRContent = template.DocumentOCRContent;
            switch (submit) {
                case "System Generation":
                    templateKeywords.GeneratedBySystem = true;
                    List<InputtedKeyword> arr = dceOps.GetKeywordsGeneratedBySystem(templateKeywords.Template);
                    templateKeywords.Keywords = dceOps.GetKeywordsGeneratedBySystem(templateKeywords.Template);
                    break;
                case "Keyword Checking":
                    if (inputKeyword.Trim() == "") {
                        ViewData["GenerateKeywordsReturnMsg"] = "Input Keyword is empty ...";
                    } else {
                        templateKeywords.GeneratedBySystem = true;
                        templateKeywords.Keywords = dceOps.GetKeywordByInput(templateKeywords.Template, inputKeyword);
                    }
                    break;
                case "Added Keywords":
                    return RedirectToAction("GenerateKeywords", new { virtualPath = virtualPath });

                case "Update":
                    DocumentsOperations docOps = new DocumentsOperations();
                    docOps.RenameDocumentTypeByVirtualPath(templateKeywords.Template.VirtualPath, templateDocType);
                    templateKeywords.Template.DocumentType = templateDocType;
                    break;
                default:
                    templateKeywords.GeneratedBySystem = false;
                    templateKeywords.Keywords = GetKeywordsByVirtualPath(virtualPath);
                    break;
            }
            return View(templateKeywords);
        }

        [HttpPost]
        public JsonResult AddKeyword(String fileID, String userName,String keyword, String rank) {
            DCEOperations dceOps = new DCEOperations();
            AuthenticationsAndAuthorizationsOperations aNaOps = new AuthenticationsAndAuthorizationsOperations();
            return new JsonResult() { Data = dceOps.InsertKeyword(new Guid(fileID), aNaOps.GetUserIDByUserName(userName), keyword.Trim(), Convert.ToDouble(rank)) };
        }

        [HttpPost]
        public JsonResult DeleteKeyword(String fileID, String userName, String keyword) {
            DCEOperations dceOps = new DCEOperations();
            AuthenticationsAndAuthorizationsOperations aNaOps = new AuthenticationsAndAuthorizationsOperations();
            return new JsonResult() { Data = dceOps.DeleteKeyword(new Guid(fileID), aNaOps.GetUserIDByUserName(userName), keyword.Trim()) };
        }

        [HttpPost]
        public JsonResult UpdateRankNumber() {
            var fileID = Request.Form["fileID"];
            var userName = Request.Form["userName"];
            var keyword = Request.Form["keyword"];
            var rankVal = Request.Form["rank"];
            DCEOperations dceOps = new DCEOperations();
            dceOps.UpdateRankByKeywordNFileID(new Guid(fileID), keyword, Convert.ToDouble(rankVal));
            return new JsonResult() { Data=true };
        }

        private List<InputtedKeyword> GetKeywordsByVirtualPath(String virtualPath) {
            DCEOperations dceOps = new DCEOperations();
            List<DCE_Keywords> keywords = dceOps.GetKeywordsByFileID(dceOps.GetFileIDFromTemplateByVirtualPath(virtualPath));
            List<InputtedKeyword> inputtedKeywords = new List<InputtedKeyword>();
            if (keywords != null) {
                foreach (DCE_Keywords keyword in keywords) {
                    InputtedKeyword inputtedKeyword = new InputtedKeyword {
                        Keyword = keyword.Keyword,
                        Rank = (decimal)keyword.Rank,
                    };

Views/RMA_DCE/AddDocument.cshtml
@{
    ViewBag.Title = "DCE - Upload Template";
}

<nav class="navbar navbar-expand-lg">
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="nav navbar-nav">
            <li class="nav-item">
                <h4 class="text-info">@ViewBag.Title</h4>
                <h6></h6>
            </li>
        </ul>
    </div>
</nav>

<div>
    <hr />
    <div class="">
        <div class="">
            <span data-toggle="modal" data-target="#UploadDocument">
                <a class="btn btn-outline-info add-tooltip text-primary" href="#">
                    Upload Template
                </a>
            </span>
        </div>
        <div class="mt-4">
            <table id="TemplatesDiv" class="table table-striped table-bordered" style="width:100%">
                <tbody>
                    <tr>
                        <td>No Records</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>

<div class="modal fade" id="UploadDocument" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title text-muted">Upload New Template</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body row">
                <div class="row mb-1 ml-1">
                    <table>
                        <tr>
                            <td><span class="text-black-50 col-md-4 col-sm-4 col-form-label">Attachment :</span></td>
                            <td><input type="file" id="uploadNewTemplate" accept=".pdf" class="form-control-file small" name="newTemplateUpload" style="line-height:38px;" /></td>
                        </tr>
                        <tr>
                            <td><span class="text-black-50 col-md-4 col-sm-4 col-form-label">Doc Type :</span></td>
                            <td><input id="uploadNewTemplateType" class="form-control" name="newTemplateType" value="" /></td>
                        </tr>
                        <tr>
                            <td><span class="text-black-50 col-md-4 col-sm-4 col-form-label">Description :</span></td>
                            <td><input id="uploadNewTemplateDesc" class="form-control" name="newTemplateDesc" value="" maxlength="200" /></td>
                        </tr>
                        <tr style="line-height: 0.7rem;">
                            <td><span class="text-black-50 col-md-4 col-sm-4 col-form-label">Skip Pages :</span></td>
                            <td>
                                <input id="uploadNewTemplateSkipPagesCheck" type="text" class="form-control col-md-4 col-sm-4" name="newTemplateSkipPagesCheck" maxlength="40" />
                                <span class="text-info" style="font-size:9px;">Enter the page number. For exameple 1,2,3</span>
                            </td>
                        </tr>
                    </table>
                </div>
            </div>
            <span id="modalUploadTemplateMsg"></span>
            <div class="modal-footer">
                <input type="submit" value="Upload" class="btn btn-outline-success" onclick="return uploadNewTemplate()" />
                <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>


<!-- DataTable JS -->
<script type="text/javascript" src="~/Scripts/datatables.min.js"></script>

<script>
    $(function () {
        getUploadedTemplates();
    });

    function reloadWebPage() { location.reload(); }

    function uploadNewTemplate() {
        $('#modalUploadTemplateMsg').html("");
        var str = $('#uploadNewTemplateSkipPagesCheck').val();
        if ($('#uploadNewTemplateType').val() == "") { $('#modalUploadTemplateMsg').html("<span class=\"small text-danger mb-4 pl-2\">Document Type cannot be empty...<\/span>"); }
        else if ($('#uploadNewTemplate').val() == "") {
            $('#modalUploadTemplateMsg').html("<span class=\"small text-danger mb-4 pl-2\">Please attach a new template ...<\/span>");
        } else if (str.match(/^$|[0-9,]+$/) == null) {
            $('#modalUploadTemplateMsg').html("<span class=\"small text-danger mb-4 pl-2\">Please follow skip page(s) pattern ...<\/span>");
        } else {
            $('#modalUploadTemplateMsg').html("<span class=\"small text-info mb-4 pl-2\">System is progressing, please wait ...<\/span>");
            var formData = new FormData();
            var totalFiles = document.getElementById("uploadNewTemplate").files.length;
            for (var i = 0; i < totalFiles; i++) {
                formData.append("File", document.getElementById("uploadNewTemplate").files[i]);
                formData.append("DocType", $("#uploadNewTemplateType").val().trim());
                formData.append("DocDesc", $("#uploadNewTemplateDesc").val().trim());
                formData.append("SkipPages", $("#uploadNewTemplateSkipPagesCheck").val().trim());
            }
            $.ajax({ url: '@Url.Action("UploadTemplate")', type: 'POST', data: formData, dataType: 'json', contentType: false, processData: false, success: function (result) { if (result != "") { alert(result); } $('#UploadDocument').modal('toggle'); $('#modalUploadTemplateMsg').html(""); $('#uploadNewTemplateType').val(""); $('#uploadNewTemplate').val(""); $('#uploadNewTemplateDesc').val("");  getUploadedTemplates(); }, error: function (result) { console.log(result); }});
        }
        return false;
    }

    function getUploadedTemplates() {
        $.ajax({url: '@Url.Action("GetUploadedTemplates")',type: 'POST',data: JSON.stringify({  }),dataType: 'json',contentType: "application/json; charset=utf-8",success: function (result) { if (result.Total > 0) {$('#TemplatesDiv').DataTable({destroy: true,info: false,data: result.Data,columns: [{ data: "Name", title: "Name" }, { data: "DocumentType", title: "Doc Type" }, { data: "VirtualPath", title: "Virtual Path" }, { data: "DateTimeUploaded", title: "Uploaded At" }, { data: "Description", title: "Description" }, { data: null, render: function (data) { var link = '@Html.ActionLink("Keywords", "GenerateKeywords", new { virtualPath = "_Data" }, new { @class = "btn btn-outline-info" })'
          link = link.replace(/\_Data/g, data.VirtualPath); var link2 = '@Html.ActionLink("Delete", null, null, new { @class= "btn btn-outline-warning ml-1", onclick= "return  deleteTemplate(\"_Path\",\"_Name\")"})'
          link2 = link2.replace(/\_Path/g, data.VirtualPath); link2 = link2.replace(/\_Name/g, data.Name); return link + " " + link2; }, targets: -1, title: "Actions" }], aoColumnDefs: [{ "width": "190px", targets: 5 }, { "visible": false, targets: 2 }, { bSortable: false, aTargets: [4,5] } ]});}},error: function (result) { console.log(result); }});
    }

    function deleteTemplate(path, fileName) {
        if (confirm("Remove template " + fileName + " permanently?")) {
            $.ajax({ url: '@Url.Action("DeleteTemplate")', type: 'POST', data: JSON.stringify({ virtualPath: path }), dataType: 'json', contentType: "application/json; charset=utf-8", success: function (result) { alert(result); }, error: function (result) { } });
            getUploadedTemplates();
        }
    }
</script>

Views/RMA_DCE/DocClassification.cshtml
@model RMA_Docker.Models.DocClassification
@{
    ViewBag.Title = "DCE - Document Classification";
}

<nav class="navbar navbar-expand-lg">
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="nav navbar-nav">
            <li class="nav-item">
                <h4 class="text-info">@ViewBag.Title</h4>
                <h6>Performing OCR and clasifying the document type</h6>
            </li>
        </ul>
    </div>
</nav>

@using (Html.BeginForm("DocClassification", "RMA_DCE", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div class="form-horizontal ">
        <hr />
        <div class="form-group">
            @Html.Label("Upload File", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBox("file", "", new { @class = "form-control-file small", type = "file" })
                @if (Model.DocClassifiedMsg != "") {
                    <span class="text-danger small">@Model.DocClassifiedMsg</span>
                }
            </div>
        </div>



        <div class="form-group mt-4">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Start OCR & Classify" class="btn btn-outline-primary add-tooltip" />
            </div>
        </div>

        <div class="form-group mt-lg-5">
            <hr />
            <div class="col-md-offset-2 col-md-auto">
                <h6 class="text-black-50 ">Result : </h6>
                @if (Model.DocClassifiedOutcome == "") {
                <span class="text-black-50 small">result required to progress before display, please wait...</span>
                } else {
                <div class="text-black-50 small">@Html.Raw(Model.DocClassifiedOutcome)</div>
                }
                
            </div>
        </div>


    </div>
}

Views/RMA_DCE/GenerateKeywords.cshtml
@model RMA_Docker.Models.TemplateKeywords
@{
    ViewBag.Title = "DCE - Generate Keywords";
}

<nav class="navbar navbar-expand-lg">
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="nav navbar-nav">
            <li class="nav-item">
                <h4 class="text-info">@ViewBag.Title</h4>
                <h6></h6>
            </li>
        </ul>
    </div>
</nav>

<!-- DataTable JS -->
<script type="text/javascript" src="~/Scripts/datatables.min.js"></script>

<div>
    <hr />
    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()
        <input type="hidden" id="templateVirtualPath" name="virtualPath" value="@Model.Template.VirtualPath" />

        <div class="form-horizontal">
            <div class="form-group">
                <div class="col-md-offset-2 col-md-auto">
                    <!-- <input type="submit" value="Save" class="btn btn-outline-success" /> -->
                    @Html.ActionLink("Back to Previous", "AddDocument", null, new { @class = "btn btn-outline-secondary" })
                </div>
            </div>

            <div class="form-group">
                @Html.Label("Document Type", new { @class = "control-label col-md-auto" })
                <div class="form-inline col-md-offset-2 col-md-auto">
                    <input id="_TemplateDocumentType" type="text" name="templateDocType" value="@Model.Template.DocumentType" class="form-control col-md-4" />
                    <input id="_SaveDocType" type="submit" name="submit" value="Update" class="btn btn-outline-success ml-3" onclick="return " />
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.TemplateOCRContent, new { @class = "control-label col-md-auto" })
                @{ if (Model.SkipPages != "")
                    { <span class="small text-black-50 text-info">- with skipped page(s) at @Model.SkipPages</span> } }
                <div class="col-md-auto">
                    @Html.TextAreaFor(model => model.TemplateOCRContent, new { id = "ocrContentTextArea", @class = "form-control", @style = "height:200px;", @readonly = "true" })
                </div>
            </div>

            <div class="form-group mt-4">
                <div class="col-md-offset-2 col-md-auto border-top pt-2">
                    <input type="submit" name="submit" value="Added Keywords" class="btn btn-outline-primary add-tooltip" data-original-title="Display all keywords" data-toggle="tooltip" />
                    <input type="submit" name="submit" value="System Generation" class="btn btn-outline-primary add-tooltip" data-original-title="Generate Keywords among uploaded templates" data-toggle="tooltip" />
                    <span data-toggle="modal" data-target="#KeywordCheckerModal">
                        <input type="button" value="Keyword Checking" class="btn btn-outline-primary add-tooltip" data-original-title="Input Keyword to check the Term Frequecy (Among All Templates)" data-toggle="tooltip" />
                    </span>
                </div>

                <div class="col-md-auto mt-3">
                    @{
                        if (Model.Keywords == null) {
                            <table id="dceKeywordDiv" class="table table-striped table-bordered" style="width:100%">
                                <tbody>
                                    <tr>
                                        <td>No Records</td>
                                    </tr>
                                </tbody>
                            </table>
                        } else {
                            if (!Model.GeneratedBySystem) { <div class="text-info btn p-0" id="downloadGeneratedDataInJson"><h6 class="small">Download Json</h6></div> }
                            <table id="dceKeywordDiv" class="table table-striped table-bordered" style="width:100%">
                                <thead>
                                    <tr>
                                        <th>Keyword</th>
                                        @if (!Model.GeneratedBySystem) { <th>Rank</th> } 
                                        else { <th>Term Frequecy (Among All Templates)</th>}
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var keyword in Model.Keywords) {
                                        <tr>
                                            <td>@keyword.Keyword</td>
                                            @if (Model.GeneratedBySystem) {
                                                <td>@keyword.GeneratedTFRate%</td>
                                                <td>
                                                    @if (!keyword.AddedFlag) {
                                                        <a href="#" class="btn btn-outline-success" id="keywordAdd" data-keywordval="@keyword.Keyword" data-tfrate="@keyword.GeneratedTFRate"><span>Add Keyword</span></a>
                                                    }
                                                </td>
                                            } else {
                                                <td contenteditable="true" id="_editableRank" class="add-tooltip text-info" data-original-title="Edit the Value and update to Server" data-toggle="tooltip">@keyword.Rank</td>
                                                <td>
                                                    <a href="#" class="btn btn-outline-info add-tooltip d-none" id="keywordRename" data-oldRankVal="@keyword.Rank" data-keywordVal="@keyword.Keyword" data-original-title="Update the Rank to Server" data-toggle="tooltip"><span>Update Rank</span></a> <a href="#" class="btn btn-outline-danger" id="keywordDelete" data-keywordVal="@keyword.Keyword"><span>Delete</span></a>
                                                </td>
                                            }
                                        </tr>
                                    }
                                </tbody>
                            </table>

                            <script>
                                $(function () {
                                    var jsDataTable = $('#dceKeywordDiv').DataTable({destroy: true,info: false,order: [[1, "desc"]],aoColumnDefs: [ { "width": "230px", targets: 2 }, { bSortable: false, aTargets: [2] }]});

                                    $('#downloadGeneratedDataInJson').on('click', function () {
                                        var path = '@Url.Action("DownloadDCETEmplateJson")' + '/?virtualPath=@Model.Template.VirtualPath';
                                        window.location.href = path;
                                    });

                                    $('#dceKeywordDiv').on('click', 'a#keywordAdd', function (event) {
                                        event.preventDefault();
                                        $.ajax({url: '@Url.Action("AddKeyword")',type: 'POST',data: JSON.stringify({fileID: "@Model.Template.FileID",userName: "@Context.User.Identity.Name",keyword: $(this).data("keywordval"),rank: $(this).data("tfrate")}),dataType: 'json',contentType: "application/json; charset=utf-8",success: function (result) { },error: function (result) { }});
                                        $(this).hide();
                                    });

                                    $('#dceKeywordDiv').on('click', 'a#keywordDelete', function (event) {
                                        if (confirm("Delete this Keyword permanently?")) {
                                            event.preventDefault();
                                            jsDataTable.row($(this).parents('tr')).remove().draw();
                                            $.ajax({ url: '@Url.Action("DeleteKeyword")', type: 'POST', data: JSON.stringify({ fileID: "@Model.Template.FileID", userName: "@Context.User.Identity.Name", keyword: $(this).data("keywordval"), rank: $(this).data("tfrate") }), dataType: 'json', contentType: "application/json; charset=utf-8", success: function (result) { }, error: function (result) { } });
                                        }
                                        return false;
                                    });

                                    $('#dceKeywordDiv').on('keydown', '#_editableRank', function (event) {
                                        $(this).parents('tr').children('td:has(a)').children('#keywordRename').removeClass("d-none");
                                    });

                                    $('#dceKeywordDiv').on('click', 'a#keywordRename', function (event) {
                                        var newRankVal = $(this).parents('tr').find('td#_editableRank').text();
                                        var formData = new FormData();
                                        formData.append("fileID", '@Model.Template.FileID');
                                        formData.append("userName", '@Context.User.Identity.Name');
                                        formData.append("keyword", $(this).data("keywordval"));
                                        formData.append("rank", newRankVal);
                                        if ($.isNumeric(newRankVal)) { if ($(this).data("oldrankval") != newRankVal) { $.ajax({ url: '@Url.Action("UpdateRankNumber")', type: 'POST', data: formData, dataType: 'json', contentType: false, processData: false, success: function (result) { console.log(result); }, error: function (result) { console.log(result); } }); } else { alert("Please change the rank value."); }} else { alert("Please enter numbers only."); }
                                    });
                                });
                            </script>
                        }
                    }
                </div>
            </div>

            <!-- Modal -->
            <div class="modal fade" id="KeywordCheckerModal" role="dialog">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h4 class="modal-title text-muted">Check Keyword's Term Frequency</h4>
                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                        </div>
                        <div class="modal-body row">
                            <span class="text-black-50 col-4 col-form-label">Keyword :</span>
                            <div class="col-8">
                                <input class="form-control" name="inputKeyword" value="" />
                            </div>
                        </div>
                        <div class="modal-footer">
                            <input type="submit" name="submit" value="Keyword Checking" class="btn btn-outline-primary" />
                            <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">Close</button>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Enf of Modal -->

        </div>
    }
</div>

<script>
    $(function () {
        $(".add-tooltip").tooltip();
        $('#_SaveDocType').hide();
        $('#_TemplateDocumentType').on('focus', function (event) { $('#_SaveDocType').show(); });
    });

    function UpdateDocumentTypeValidation(oldDocTye) {
        var docTypeName = $('#_TemplateDocumentType').val().trim();
        if (docTypeName != null && docTypeName != oldDocTye) { return true; }
        return false;
    }
</script>